# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38a870cdc7f41175fd49a52689539f9d"
application_url = "https://stock-alert.nazmulcodes.org/app"
embedded = true
name = "Stock Alert"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_inventory,write_products,read_locations,read_orders,read_files"


[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/subscriptions_update"
  topics = [ "app_subscriptions/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/create", "products/delete", "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[app_proxy]
url = "https://stock-alert.nazmulcodes.org/api"
subpath = "stock-alert"
prefix = "apps"

[pos]
embedded = false

[auth]
redirect_urls = [
  "https://stock-alert.nazmulcodes.org/auth/callback",
  "https://stock-alert.nazmulcodes.org/auth/shopify/callback",
  "https://stock-alert.nazmulcodes.org/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
