# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4c382e2cb454fd7c45b655248b2d1f7"
name = "Stock Alert Dev"
handle = "stock-alert-dev-1"
application_url = "https://dev.nazmulcodes.org"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stock-alert-2.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://dev.nazmulcodes.org/auth/callback",
  "https://dev.nazmulcodes.org/auth/shopify/callback",
  "https://dev.nazmulcodes.org/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

# Mandatory compliance webhooks
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/api/webhooks/compliance"

# Inventory webhooks
[[webhooks.subscriptions]]
topics = ["inventory_levels/update", "products/update", "products/delete"]
uri = "/api/webhooks/inventory"

[pos]
embedded = false
