# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38a870cdc7f41175fd49a52689539f9d"
name = "Stock Alert"
handle = "stock-alert-27"
application_url = "https://stock-alert.nazmulcodes.org"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stock-alert-2.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://stock-alert.nazmulcodes.org/auth/callback",
  "https://stock-alert.nazmulcodes.org/auth/shopify/callback",
  "https://stock-alert.nazmulcodes.org/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
