# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38a870cdc7f41175fd49a52689539f9d"
application_url = "https://nco-stock-alert.fly.dev"
embedded = true
name = "Stock Alert"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_inventory,write_products,read_locations"


[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products"
  topics = [ "products/delete", "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false

[auth]
redirect_urls = [
  "https://nco-stock-alert.fly.dev/auth/callback",
  "https://nco-stock-alert.fly.dev/auth/shopify/callback",
  "https://nco-stock-alert.fly.dev/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
